"""Single source of truth for War Room OS release identity."""
from __future__ import annotations
RELEASE_VERSION='9.8'
RELEASE_NAME='Unified Decision Packet'
RELEASE_ID=f'War Room OS V{RELEASE_VERSION}'
SCHEMA_PREFIX='warroom.v98'
CAPITAL_PERMISSION='BLOCKED_UNTIL_EXACT_PROOF_AND_HUMAN_APPROVAL'
OPERATIONAL_PERMISSION='CURRENT_CONTEXT_UNIFIED_TICKER_PACKET_RISK_CHECK_MANUAL_EXPORT_RECONCILIATION'
