from __future__ import annotations
import json,math,sys
from pathlib import Path
import numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parent;sys.path.insert(0,str(ROOT))
from cusp_fragility_v73 import CuspEstimator,cusp_geometry,fit_logistic,probability_metrics,decision_metrics,gaussian_fit,gaussian_logpdf,quadratic_expand,simultaneous_bootstrap_lower,sha256_file,trailing_rms_prior,future_min_return
from research_v55.flat_parquet_snappy import read_flat_parquet
PROTOCOL=ROOT/'research_v57/V75_PRE1973_CUSP_PROTOCOL_FROZEN.json';RECEIPT=ROOT/'research_v57/V75_LOCKBOX_OPEN_RECEIPT.json';RESULT=ROOT/'research_v57/results/V75_PRE1973_CUSP_RESULTS.json'
BASE=['rv12','drawdown12','trend12','log_cape','real_rate','gold12','cpi_yoy_change12'];ALPHA=['real_rate','drawdown12','cpi_yoy_change12'];BETA=['log_cape','trend12','gold12']
def perll(y,p):p=np.clip(p,1e-6,.999999);return -(y*np.log(p)+(1-y)*np.log(1-p))
def mask(i,a,b):return(i>=pd.Timestamp(a))&(i<=pd.Timestamp(b))
def main():
 if RESULT.exists():raise SystemExit('exists')
 rec=json.loads(RECEIPT.read_text());checks={'protocol':sha256_file(PROTOCOL)==rec['protocol_sha256'],'runner':sha256_file(__file__)==rec['runner_sha256'],'macro':sha256_file(ROOT/'research/macro_panel.parquet')==rec['macro_sha256']}
 if not all(checks.values()):raise SystemExit(str(checks))
 m=read_flat_parquet(ROOT/'research/macro_panel.parquet').loc['1881-01-01':'1972-12-01'];l=np.log(m.spx);r=l.diff();rms=trailing_rms_prior(r,12)
 f=pd.DataFrame(index=m.index);f['state_z']=(r/(rms+1e-12)).clip(-5,5);f['rv12']=rms*np.sqrt(12);f['drawdown12']=m.spx/m.spx.rolling(12,min_periods=12).max()-1;f['trend12']=l-l.shift(12);f['log_cape']=np.log(m.cape.clip(lower=1e-12));f['real_rate']=m.rate10-m.cpi_yoy;f['gold12']=np.log(m.gold/m.gold.shift(12));f['cpi_yoy_change12']=m.cpi_yoy-m.cpi_yoy.shift(12);f['fwd_min_6m']=future_min_return(m.spx,6);f['target']=(f.fwd_min_6m<=-.10).astype(float);f.loc[f.fwd_min_6m.isna(),'target']=np.nan;f=f.dropna(subset=['state_z','target']+BASE+ALPHA+BETA)
 masks={'train':mask(f.index,'1882-01-01','1928-12-01'),'validation':mask(f.index,'1929-07-01','1950-12-01'),'lockbox':mask(f.index,'1951-07-01','1972-06-01')};tr=np.where(masks['train'])[0];va=np.where(masks['validation'])[0];lo=np.where(masks['lockbox'])[0];y=f.target.to_numpy(int)
 est=CuspEstimator();fit=est.fit(f.state_z.to_numpy()[tr],f[ALPHA].to_numpy()[tr],f[BETA].to_numpy()[tr],starts=(0,1,2,3));a,b=est.alpha_beta(fit,f[ALPHA].to_numpy(),f[BETA].to_numpy());ys=fit.params[0]+math.exp(fit.params[1])*f.state_z.to_numpy();g=cusp_geometry(a,b,ys)
 c=np.column_stack([f[ALPHA],f[BETA]]);clp=est.score_samples(fit,f.state_z.to_numpy(),f[ALPHA].to_numpy(),f[BETA].to_numpy());lc,ls=gaussian_fit(c[tr],f.state_z.to_numpy()[tr]);llp=gaussian_logpdf(c,f.state_z.to_numpy(),lc,ls);q=quadratic_expand(c);qc,qs=gaussian_fit(q[tr],f.state_z.to_numpy()[tr]);qlp=gaussian_logpdf(q,f.state_z.to_numpy(),qc,qs);struct={s:{'cusp':float(clp[ix].mean()),'linear':float(llp[ix].mean()),'quadratic':float(qlp[ix].mean())} for s,ix in [('validation',va),('lockbox',lo)]};sp=all(struct[s]['cusp']>struct[s][k] for s in struct for k in ['linear','quadratic'])
 xb=f[BASE].to_numpy();xc=np.column_stack([xb,g]);xs=np.column_stack([xb,a,b,a*a,b*b,a*b]);rng=np.random.default_rng(750076);xsh=np.column_stack([xb,g[rng.permutation(len(g))]]);xsi=np.column_stack([xb,np.roll(g,60,axis=0)]);XX={'baseline':xb,'cusp':xc,'smooth':xs,'shuffle':xsh,'shift60':xsi};mods={k:fit_logistic(v[tr],y[tr]) for k,v in XX.items()};met={};pr={}
 for k,md in mods.items():
  pt=md.predict_proba(XX[k][tr])[:,1];pv=md.predict_proba(XX[k][va])[:,1];pl=md.predict_proba(XX[k][lo])[:,1];pr[k]={'train':pt,'validation':pv,'lockbox':pl};met[k]={'validation':{'probability':probability_metrics(y[va],pv),'decision':decision_metrics(y[tr],pt,y[va],pv,len(va))},'lockbox':{'probability':probability_metrics(y[lo],pl),'decision':decision_metrics(y[tr],pt,y[lo],pl,len(lo))}}
 def boot(k):return simultaneous_bootstrap_lower([(y[va]-pr['baseline']['validation'])**2-(y[va]-pr[k]['validation'])**2,perll(y[va],pr['baseline']['validation'])-perll(y[va],pr[k]['validation']),(y[lo]-pr['baseline']['lockbox'])**2-(y[lo]-pr[k]['lockbox'])**2,perll(y[lo],pr['baseline']['lockbox'])-perll(y[lo],pr[k]['lockbox'])],4000,12,750075)
 bt=boot('cusp');bs=boot('shuffle');bi=boot('shift60');gates={'structural_density_pass':sp,'four_point_positive':all(x>0 for x in bt['observed']),'simultaneous_lower_positive':all(x>0 for x in bt['simultaneous_lower']),'not_worse_than_smooth':all(met['cusp'][s]['probability'][q]<=met['smooth'][s]['probability'][q]+1e-12 for s in ['validation','lockbox'] for q in ['brier','log_loss']),'placebo_shuffle_fails':not all(x>0 for x in bs['simultaneous_lower']),'placebo_shift_fails':not all(x>0 for x in bi['simultaneous_lower'])};support=all(gates.values());out={'study_id':'V75_PRE1973_CUSP_REGIME_DEPENDENCE','receipt_checks':checks,'rows':{k:int(v.sum()) for k,v in masks.items()},'positive_rows':{'train':int(y[tr].sum()),'validation':int(y[va].sum()),'lockbox':int(y[lo].sum())},'structural_fit':struct,'metrics':met,'bootstrap':bt,'placebos':{'shuffle':bs,'shift60':bi},'gates':gates,'historical_regime_support':support,'promoted_current':False,'live_decision_weight':0.0,'capital_permission':'BLOCKED','verdict':'PRE_MODERN_ONLY_SUPPORT' if support else 'NOT_PROVEN'};RESULT.write_text(json.dumps(out,indent=2,sort_keys=True));print(json.dumps({'verdict':out['verdict'],'rows':out['rows'],'positive_rows':out['positive_rows'],'gates':gates,'bootstrap':bt},indent=2))
if __name__=='__main__':main()
