"""Classify every tracked file into audit classes and (with --apply) execute
the safe subset of moves/deletions via git.

Classes:
  A ACTIVE PRODUCTION        - strict production reachability (22 files)
  B ACTIVE TEST/VALIDATION   - tests/, hardening_tests/ closure, src/, validate_all.py
  C REQUIRED RESEARCH        - warroom/, engines/, gcfis/, alpha_foundry/, research/, data/
  D ARCHIVAL                 - superseded version artifacts -> research/archive/
  E GENERATED/TEMPORARY      - pyc, caches, generated exports -> delete + .gitignore
  F DEAD                     - unreferenced scratch files -> delete

Run `python tools/audit/classify_files.py` for a dry-run plan, then
`python tools/audit/classify_files.py --apply` to execute.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
OUT = REPO / "docs" / "audit"
ARCHIVE = "research/archive"

KEPT_DIRS = (
    "tests/", "hardening_tests/", "src/", "scripts/", "config/", "data/",
    "evidence/", "evidence_templates/", "validation/", "ops/", "migration/",
    "warroom/", "engines/", "gcfis/", "alpha_foundry/", "research/", "docs/",
    "tools/", ".streamlit/", "bootstrap_evidence/",
)

ESSENTIALS = {
    "README.md", "requirements.txt", "requirements-dev.txt",
    "requirements-streaming.txt", "pyproject.toml", "Dockerfile",
    "docker-compose.yml", "Makefile", ".env.example", "FEED_CONFIG.env.example",
    "V101_TRADING.env.example", "VALIDATION.md", "DATA_CONNECTORS.md",
    "WHAT_IS_AND_IS_NOT_PROVEN.md", "V101_OPERATOR_GUIDE.md",
    "V101_RELEASE_STATUS.md",
}

DELETE_EXACT = {
    "_v.js", "_v2.js", "decision_packet_v98.py.bak", "dashboard_live.html",
    "desk_data.json", "V63_TAB_MODEL_AUDIT.json", "V64_TAB_MODEL_AUDIT.json",
    ".cache/dashboard_validate.js", ".cache/.gitkeep",
    "OFFLINE_CONNECTION_TEST_REPORT.json", "LIVE_STACK_TEST_REPORT.json",
}

DELETE_REASONS = {
    "_v.js": "scratch dashboard JS, zero references",
    "_v2.js": "scratch dashboard JS, zero references",
    "decision_packet_v98.py.bak": "editor backup of superseded file",
    "dashboard_live.html": "generated by `run.py --html`; regenerable output",
    "desk_data.json": "generated by `run.py --out`; regenerable output",
    "V63_TAB_MODEL_AUDIT.json": "generated audit output (1 MB), regenerable",
    "V64_TAB_MODEL_AUDIT.json": "generated audit output (1 MB), regenerable",
    ".cache/dashboard_validate.js": "cache content; caches must not be tracked",
    ".cache/.gitkeep": "cache directory is being gitignored wholesale",
    "OFFLINE_CONNECTION_TEST_REPORT.json": "generated run output, superseded by docs/audit/TEST_RESULTS.md",
    "LIVE_STACK_TEST_REPORT.json": "generated run output, superseded by docs/audit/TEST_RESULTS.md",
}


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True, check=True).stdout


def main() -> int:
    apply = "--apply" in sys.argv
    tracked = git("ls-files").splitlines()
    reachable = set(json.loads((OUT / "import_graph.json").read_text())["edges"].keys()) - set(
        json.loads((OUT / "import_graph.json").read_text())["unreachable_files"]
    )

    classes: dict[str, str] = {}
    reasons: dict[str, str] = {}

    # --- class E/F deletions: pyc + explicit scratch/generated ---
    for f in tracked:
        if f.endswith(".pyc") or "__pycache__/" in f:
            classes[f] = "E"
            reasons[f] = "compiled bytecode must never be tracked"
        elif f in DELETE_EXACT:
            classes[f] = "E"
            reasons[f] = DELETE_REASONS[f]
        elif f.startswith("outputs/"):
            classes[f] = "E"
            reasons[f] = "generated synthetic-demo output, regenerable via tests/generate_synthetic_demo.py"

    # --- keep set fixpoint: only *read-context* references keep a root file ---
    # A name mentioned in a comment/report string does not; a name on a line with
    # open/read_text/read_csv/json.load/atomic_json/path-construction does.
    keep = {f for f in reachable if not f.startswith("research/archive/")} | ESSENTIALS
    keep |= {f for f in tracked if f.startswith(KEPT_DIRS)}
    keep -= set(classes)  # deletions win

    word = re.compile(r"[A-Za-z0-9_]+\.(?:py|json|csv|html|md|txt|png|parquet|env\.example)")
    read_hint = re.compile(
        r"open\(|read_text|read_csv|read_parquet|json\.load|atomic_json|read_bytes|"
        r"read_valid|_load\(|load\(|HERE\s*/|Path\("
    )
    changed = True
    while changed:
        changed = False
        for f in sorted(keep):
            p = REPO / f
            if not p.is_file() or p.stat().st_size > 8_000_000 or f.endswith((".png", ".parquet", ".pyc")):
                continue
            try:
                lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
            except Exception:
                continue
            for line in lines:
                if not read_hint.search(line):
                    continue
                for m in word.finditer(line):
                    name = m.group(0)
                    if name in tracked and name not in keep and name not in classes:
                        keep.add(name)
                        changed = True

    # --- classify the rest ---
    for f in tracked:
        if f in classes or f in keep:
            continue
        top = f.split("/")[0]
        if top in {".cache", "outputs"}:
            classes[f] = "E"
            reasons[f] = "generated cache/output content"
        elif top in {"artifacts", "legacy", "legacy_v42_audit", "legacy_v52_release"}:
            classes[f] = "D"
            reasons[f] = "historical validation artifacts, consolidated under research/archive"
        elif "/" not in f:
            classes[f] = "D"
            reasons[f] = "superseded version artifact, unreachable from runtime/tests"
        else:
            keep.add(f)  # nested files in kept dirs

    # --- .bat launchers: keep only if every referenced .py survives ---
    for f in sorted(keep):
        if not f.endswith((".bat", ".ps1")):
            continue
        content = (REPO / f).read_text(encoding="utf-8", errors="replace")
        pyrefs = [m.group(0) for m in word.finditer(content) if m.group(0).endswith(".py")]
        missing = [r for r in pyrefs if r in classes]
        if missing:
            keep.discard(f)
            classes[f] = "D"
            reasons[f] = f"launcher for archived scripts ({', '.join(missing[:3])})"

    # --- assign class labels for kept files ---
    prod = set(json.loads((OUT / "production_reachable.json").read_text()))
    label = {}
    for f in tracked:
        if f in classes:
            label[f] = classes[f]
        elif f in prod:
            label[f] = "A"
        elif f.startswith(("tests/", "hardening_tests/", "src/", "scripts/")) or f in reachable:
            label[f] = "B"
        else:
            label[f] = "C"

    moves = {f: f"{ARCHIVE}/{f}" for f, c in label.items() if c == "D"}
    deletes = sorted(f for f, c in label.items() if c in {"E", "F"})

    plan = {"keep_counts": {}, "move_count": len(moves), "delete_count": len(deletes),
            "moves": moves, "deletes": deletes, "reasons": reasons, "labels": label}
    from collections import Counter
    plan["keep_counts"] = dict(Counter(label.values()))
    (OUT / "cleanup_plan.json").write_text(json.dumps(plan, indent=1) + "\n", encoding="utf-8")
    print(json.dumps({"class_counts": plan["keep_counts"], "moves": len(moves), "deletes": len(deletes)}, indent=2))

    if not apply:
        print("DRY RUN — re-run with --apply to execute")
        return 0

    for f in deletes:
        subprocess.run(["git", "rm", "-q", "--", f], cwd=REPO, check=True)
    for src, dst in sorted(moves.items()):
        target = REPO / dst
        target.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "mv", src, dst], cwd=REPO, check=True)
    print(f"applied: {len(deletes)} deletions, {len(moves)} moves")
    return 0


if __name__ == "__main__":
    sys.exit(main())
